name: Setup Opened Discussions

on:
  discussion:
    types:
      - opened

jobs:
  label_discussion:
    runs-on: ubuntu-latest
    permissions:
      discussions: write
      contents: read

    steps:
      - name: Label discussion by author team
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { discussion, repository } = context.payload;
            const author = discussion.user.login;

            const feTeam = ['keemsebin', 'ExceptAnyone', 'yeji0214'];
            const beTeam = ['joon6093', 'abc5259', 'praisebak', 'jumdo12'];

            let label = null;
            if (feTeam.includes(author)) label = 'fe';
            else if (beTeam.includes(author)) label = 'be';

            if (label) {
              await github.rest.issues.addLabels({
                owner: repository.owner.login,
                repo: repository.name,
                issue_number: discussion.number,
                labels: [label],
              });
            } else {
              console.log(`No team match found for user: ${author}`);
            }
