name: Setup Created Discussions

on:
  discussion:
    types:
      - created

jobs:
  label_discussion:
    runs-on: ubuntu-latest
    permissions:
      discussions: write
      contents: read

    steps:
      - name: Set labels
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { discussion, repository } = context.payload;
            const author = discussion.user.login;

            const feTeam = ['keemsebin', 'ExceptAnyone', 'yeji0214'];
            const beTeam = ['joon6093', 'abc5259', 'praisebak', 'jumdo12'];

            const LABELS = {
              be: 'LA_kwDOMGIpFc8AAAACFBS_mw',
              fe: 'LA_kwDOMGIpFc8AAAACFFXVLA'
            };

            let labelNodeId = null;
            if (feTeam.includes(author)) labelNodeId = LABELS.fe;
            else if (beTeam.includes(author)) labelNodeId = LABELS.be;

            if (!labelNodeId) return;

            await github.graphql(`
              mutation($discussionId: ID!, $labelIds: [ID!]!) {
                addLabelsToLabelable(input: {
                  labelableId: $discussionId,
                  labelIds: $labelIds
                }) {
                  clientMutationId
                }
              }
            `, {
              discussionId: discussion.node_id,
              labelIds: [labelNodeId]
            });

      - name: Send notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          AUTHOR="${{ github.event.discussion.user.login }}"
          TITLE="${{ github.event.discussion.title }}"
          URL="${{ github.event.discussion.html_url }}"

          curl -X POST -H 'Content-type: application/json' \
            --data "{
              \"text\": \"💬 새 Discussion이 생성되었습니다!\n*작성자:* ${AUTHOR}\n*제목:* ${TITLE}\n👉 <${URL}|Discussion 바로가기>\"
            }" \
            $SLACK_WEBHOOK_URL
